kind: pipeline
name : xKernel Compiler
version: rev1.5_template
steps:
 - name: Kernel Deploy
   image: nexgang/ubuntu:latest
   environment:
     KERNEL_NAME:
       from_secret: KERNEL_NAME
     ANYKERNEL:
       from_secret: ANYKERNEL
     TG_TOKEN:
       from_secret: TG_TOKEN
     TG_CHAT_ID:
       from_secret: TG_CHAT_ID
   commands:
     - bash kernel_build.sh
